server.port: 8702

spring:
  application:
    name: configservice
  profiles:
    active: development
  cloud:
    config:
      server:
        git:
          uri: https://github.com/tkmcnally-tmg/spring-cloud-config.git
          skip-ssl-validation: true